spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/inc?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password:

pic:
  path: C:/files/image/
  prefix: C:/files/image/